video_name: 蜀西路左出右进.mp4
video_path: H:\2026年项目文件夹\09-12号线规划统筹\蜀西路左出右进.mp4
entries:
  进城主道:
    lines:
    - line_id: line_8f83328e
      entry_name: 进城主道
      direction: 直行
      x1: 447
      y1: 378
      x2: 591
      y2: 377
      color:
      - 231
      - 76
      - 60
      is_drawn: true
  进城辅道:
    lines:
    - line_id: line_696e91f9
      entry_name: 进城辅道
      direction: 直行
      x1: 599
      y1: 366
      x2: 702
      y2: 365
      color:
      - 52
      - 152
      - 219
      is_drawn: true
  出城主道:
    lines:
    - line_id: line_0097cf72
      entry_name: 出城主道
      direction: 直行
      x1: 444
      y1: 363
      x2: 333
      y2: 364
      color:
      - 46
      - 204
      - 113
      is_drawn: true
  出城辅道:
    lines:
    - line_id: line_564e014b
      entry_name: 出城辅道
      direction: 直行
      x1: 330
      y1: 359
      x2: 224
      y2: 357
      color:
      - 155
      - 89
      - 182
      is_drawn: true
